### ISSUE TITLE
Your models might be too large? Moving around in viewport is slow

### ISSUE THREAD

**Issue by lesleyrs** [samOtero/PTD_Game_Godot#2]
https://i.imgur.com/6V1cr3U.png - your game with floor hidden

https://i.imgur.com/RxFrIlh.png - my test project with some slightly called down models

I haven't really used 3d yet so I can't give a definite answer for this, but even sped up viewport movement (right click+shift+arrow keys) felt quite slow and got old fast.

Might have to shrink models or just scale them down in the editor itself which is quite easy.

**Comment by samOtero** [comment]
Good point! I will look into this, I did noticed moving was slow as well!

**Comment by samOtero** [comment]
Scales seems okay to me, I did found a workaround for the view port as detailed here: https://www.reddit.com/r/godot/comments/bn532c/comment/en3t04p/?utm_source=share&utm_medium=web2x&context=3

Basically click on the unit then put your mouse over the 3d viewport and press F, it will zoom in and moving should be faster.

**Comment by lesleyrs** [comment]
Yea that's useful but it still feels slow, you can change freelook speed in editor settings but that's independent of project so not the most convenient.

At current size of the area it's not the biggest deal, but if you make it any bigger :turtle:

**Comment by lesleyrs** [comment]
I changed the GameRoot size to 0.1 and it feels much better, but it seems the child nodes of Path1 have to be changed manually (to 0.05).

I also recommend using Snap (the magnet icon above viewport) and if you add a collision shape to the ground you can do PgDn on numpad to snap objects to the floor (or click Transform>Snap Object to Floor) also above the viewport.
